### ISSUE TITLE
完全按照说明用vs2019打开cmake方式编译，却运行不了

### ISSUE THREAD

**Issue by cvwet** [startalkIM/startalk_pc#4]
![Uploading 微信图片_20201112211040.png…]()

**Comment by cvwet** [comment]
![微信图片_20201112211040](https://user-images.githubusercontent.com/28288141/98944980-d6f37400-252c-11eb-80f8-a6e5cda30e05.png)

**Comment by ChaoCcWang** [comment]
这个问题应该是本地qt版本与编译的qt版本不匹配导致的. (例如. 编译了x86版本, 但是环境变量配置的是x64版本)

**Comment by cvwet** [comment]
> 这个问题应该是本地qt版本与编译的qt版本不匹配导致的. (例如. 编译了x86版本, 但是环境变量配置的是x64版本)

谢谢回复，各种组合都试过了，问题依旧

**Comment by cvwet** [comment]
> 这个问题应该是本地qt版本与编译的qt版本不匹配导致的. (例如. 编译了x86版本, 但是环境变量配置的是x64版本)

你说得对，逐条分析编译输出信息，原来是调用了anaconda3里面的QT，导致系列问题，卸掉anaconda3，就能运行了。

但是又有新问题，程序运行看不到主窗口，只有右下角任务栏的图标，怎么点击都出不来，心累。。。

**Comment by ChaoCcWang** [comment]
这个问题应该是登录窗模块加载失败, 常见的问题是没有安装qt的web模块 
可以参考 https://github.com/startalkIM/startalk_pc/wiki/Install-Instructions#windows%E8%BD%AF%E4%BB%B6%E5%AE%89%E8%A3%85 中的Qt模块安装

> 安装时请手动添加 "Qt WebEngine"、和 "Qt Network Authorization"模块。
